name: build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build_steer_infantry_cs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          # When running on pull_request we want to checkout the PR head commit
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: ./.github/actions/build-target
        with:
          target: steer_infantry_cs
          build_type: ${{ env.BUILD_TYPE }}
  build_drone_gb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: ./.github/actions/build-target
        with:
          target: build_drone_gb
          build_type: ${{ env.BUILD_TYPE }}
