name: build

on:
  workflow_dispatch: {}

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: List targets
        run: |
          echo "This repository now uses per-target workflows with badges:"
          echo "- build-steer_infantry_cs"
          echo "- build-drone_gb"
