name: Static analysis

on: pull_request

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      # OPTIONAL: auto-closing conversations requires the `contents` permission
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy
      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
      - name: Prepare compile_commands.json
        run: cmake --preset Debug -G "Unix Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Analyze
        run: ./run-clang-tidy.sh --export
      - name: Process clang-tidy warnings
        uses: asarium/clang-tidy-action@v1
        with:
          fixesFile: clang-tidy-result/fixes.yaml